POST http://localhost:8080/test/endpoint
Accept: application/json
Content-Type: application/json
Request-ID: req-ID-1234
Cookie: cookieName=coooooookie

{
  "someValue": "TEST_VAL",
  "another": "anything",
  "count": 11,
  "maxDateAdded": "03-12-2021"
}